### ISSUE TITLE
Hello, what I want to ask is that there is no environment.py in your project

### ISSUE THREAD

**Issue by 17719108990** [cleverchou/sfc_placement#2]
tensorflow==1.8.0
matplotlib
pymzn==0.17.0
jinja2
tqdm
pygmo

_Originally posted by @cleverchou in https://github.com/cleverchou/sfc_placement/issues/1#issuecomment-1512389198_

**Comment by cleverchou** [comment]
https://github.com/cleverchou/sfc_placement/blob/master/environment.py
